#!/usr/bin/env bash
# Idempotent setup for the dedicated snny.ai Cloudflare tunnel (snny-ingress spec).
#
# Exposes THIS host's Sunny gateway at https://snny.ai (and www.snny.ai) through a
# named cloudflared tunnel owned by this project — deliberately independent of any
# other tunnel on the machine (e.g. devbox's): its own tunnel name, credentials,
# config file, and systemd user unit. The only dependencies are the `cloudflared`
# binary and a Cloudflare account holding the snny.ai zone.
#
# Prereqs (one-time, interactive):
#   - `cloudflared tunnel login` completed with a cert that can see the snny.ai zone
#     (~/.cloudflared/cert.pem — NOTE: the cert selects the account/zone; a mismatched
#     cert silently routes DNS in the wrong zone).
#   - snny.ai zone active in that Cloudflare account.
#
# Safe to re-run: converges to the same state without duplicating tunnels, DNS
# records, or units.
set -euo pipefail

TUNNEL_NAME="${SNNY_TUNNEL_NAME:-snny}"
DOMAIN="${SNNY_DOMAIN:-snny.ai}"
LOCAL_PORT="${PORT:-8789}"
CONFIG_DIR="${HOME}/.config/sunny"
CONFIG_FILE="${CONFIG_DIR}/cloudflared-snny.yml"
UNIT_NAME="sunny-snny-tunnel.service"
UNIT_FILE="${HOME}/.config/systemd/user/${UNIT_NAME}"

command -v cloudflared >/dev/null || {
  echo "error: cloudflared not found on PATH (install it or run devbox's bootstrap first)" >&2
  exit 1
}

# 1. Create the tunnel if it doesn't exist; either way, resolve its UUID.
if ! cloudflared tunnel list --output json | grep -q "\"name\": *\"${TUNNEL_NAME}\""; then
  echo "creating tunnel '${TUNNEL_NAME}'..."
  cloudflared tunnel create "${TUNNEL_NAME}"
fi
TUNNEL_ID=$(cloudflared tunnel list --output json |
  python3 -c "import json,sys; print(next(t['id'] for t in json.load(sys.stdin) if t['name']=='${TUNNEL_NAME}'))")
CREDS_FILE="${HOME}/.cloudflared/${TUNNEL_ID}.json"
[ -f "${CREDS_FILE}" ] || {
  echo "error: credentials file ${CREDS_FILE} missing — was the tunnel created on another machine?" >&2
  exit 1
}
echo "tunnel '${TUNNEL_NAME}' id: ${TUNNEL_ID}"

# 2. Write OUR config (never touches ~/.cloudflared/config.yml — that one belongs
#    to whatever other tunnel runs on this host).
mkdir -p "${CONFIG_DIR}"
cat > "${CONFIG_FILE}" <<EOF
# Generated by scripts/setup-snny-tunnel.sh — re-run that script to change.
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS_FILE}
ingress:
  - hostname: "${DOMAIN}"
    service: http://localhost:${LOCAL_PORT}
  - hostname: "www.${DOMAIN}"
    service: http://localhost:${LOCAL_PORT}
  - service: http_status:404
EOF
echo "wrote ${CONFIG_FILE} (→ http://localhost:${LOCAL_PORT})"

# 3. Route DNS (idempotent: cloudflared refuses dupes with 'record already exists',
#    which we tolerate; any OTHER failure is fatal).
#
#    GOTCHA (bit us 2026-07-15): cloudflared's cert (~/.cloudflared/cert.pem) is
#    ZONE-scoped by the `tunnel login` flow. If the cert was minted for a different
#    zone (e.g. waywardlane.com), `route dns snny snny.ai` exits 0 but silently
#    creates `snny.ai.<other-zone>` in the WRONG zone. So never trust the exit code
#    alone — verify the record actually exists at the zone's authoritative NS below.
#    To use a snny-scoped cert without clobbering the default one, save it elsewhere
#    and export TUNNEL_ORIGIN_CERT=<path> before running this script.
for host in "${DOMAIN}" "www.${DOMAIN}"; do
  if out=$(cloudflared tunnel route dns "${TUNNEL_NAME}" "${host}" 2>&1); then
    echo "dns: ${host} route command accepted"
  elif grep -qi "already exists\|already configured" <<<"${out}"; then
    echo "dns: ${host} route already present (per cloudflared)"
  else
    echo "error: dns route for ${host} failed:" >&2
    echo "${out}" >&2
    exit 1
  fi
done

# 3b. VERIFY at the authoritative nameserver (instant on Cloudflare — no propagation
#     excuse): the proxied CNAME must answer as flattened A records or a CNAME.
ZONE_NS=$(dig NS "${DOMAIN}" +short @1.1.1.1 | head -1)
[ -n "${ZONE_NS}" ] || {
  echo "error: cannot find nameservers for ${DOMAIN} — is the zone active in Cloudflare?" >&2
  exit 1
}
# 3c. VERIFY + SELF-HEAL record CONTENT via the API (cloudflared 2026.5.2 bug,
#     observed live 2026-07-15: `route dns snny <host>` resolved the tunnel NAME to a
#     DIFFERENT tunnel's ID — records existed but routed to the wrong tunnel). The
#     cert minted by `tunnel login` embeds a zone-scoped API token; use it to check
#     each record points at OUR tunnel and patch it if not. Token stays in-shell.
CERT_PATH="${TUNNEL_ORIGIN_CERT:-${HOME}/.cloudflared/cert.pem}"
API_TOKEN=$(sed -n '/ARGO TUNNEL TOKEN/,/END/p' "${CERT_PATH}" | grep -v -- '-----' | tr -d '\n' |
  base64 -d 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin).get('apiToken',''))" || true)
EXPECTED="${TUNNEL_ID}.cfargotunnel.com"
if [ -n "${API_TOKEN}" ]; then
  ZONE_ID=$(curl -sS -m 15 -H "Authorization: Bearer ${API_TOKEN}" \
    "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}" |
    python3 -c "import json,sys; r=json.load(sys.stdin)['result']; print(r[0]['id'] if r else '')")
  if [ -n "${ZONE_ID}" ]; then
    for host in "${DOMAIN}" "www.${DOMAIN}"; do
      rec=$(curl -sS -m 15 -H "Authorization: Bearer ${API_TOKEN}" \
        "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?name=${host}" |
        python3 -c "import json,sys; r=json.load(sys.stdin)['result']; print(f\"{r[0]['id']} {r[0]['content']}\" if r else '')")
      rec_id="${rec%% *}"
      rec_content="${rec#* }"
      if [ -n "${rec_id}" ] && [ "${rec_content}" != "${EXPECTED}" ]; then
        echo "dns: ${host} points at ${rec_content} — patching to ${EXPECTED}"
        curl -sS -m 15 -X PATCH -H "Authorization: Bearer ${API_TOKEN}" -H "Content-Type: application/json" \
          -d "{\"content\":\"${EXPECTED}\"}" \
          "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${rec_id}" >/dev/null
      elif [ -n "${rec_id}" ]; then
        echo "dns: ${host} content verified (${EXPECTED})"
      fi
    done
  fi
else
  echo "warn: could not extract API token from ${CERT_PATH} — skipping content verification" >&2
fi

for host in "${DOMAIN}" "www.${DOMAIN}"; do
  if [ -z "$(dig +short A "${host}" @"${ZONE_NS}")$(dig +short CNAME "${host}" @"${ZONE_NS}")" ]; then
    cat >&2 <<EOF
error: ${host} has NO record at ${ZONE_NS} — cloudflared routed it into the wrong
zone (its cert is scoped to a different domain). Fix one of these ways:
  a) In the Cloudflare dashboard, add a proxied CNAME in the ${DOMAIN} zone:
       ${host} → ${TUNNEL_ID}.cfargotunnel.com
  b) Mint a cert for the ${DOMAIN} zone WITHOUT clobbering the default one:
       TUNNEL_ORIGIN_CERT=~/.cloudflared/cert-snny.pem cloudflared tunnel login
     (pick ${DOMAIN} in the browser), then re-run this script with
       TUNNEL_ORIGIN_CERT=~/.cloudflared/cert-snny.pem
Also check the wrong zone for junk '${host}.<other-domain>' records to delete.
EOF
    exit 1
  fi
  echo "dns: ${host} verified at ${ZONE_NS}"
done

# 4. Install + enable the systemd user unit (boot-start assumes linger is already
#    enabled on this host, as devbox's bootstrap does).
mkdir -p "$(dirname "${UNIT_FILE}")"
cat > "${UNIT_FILE}" <<EOF
[Unit]
Description=Cloudflare tunnel for ${DOMAIN} (Sunny short links + callbacks)
After=network-online.target

[Service]
ExecStart=$(command -v cloudflared) tunnel --no-autoupdate --config ${CONFIG_FILE} run
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now "${UNIT_NAME}"
echo "unit ${UNIT_NAME}: $(systemctl --user is-active "${UNIT_NAME}")"

echo
echo "done. verify:  curl -sS https://${DOMAIN}/health"
echo "then set SHORT_LINK_BASE_URL=https://${DOMAIN} in .env (takes effect on next restart)."
